name: Superstition Mountains
favicon: null
layout_spectrum: 0.5562047439161688
typography_spectrum: 0.5057614520192146
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.8717408664524555
  lightness: 0.5143175979610533
  saturation: 0.29860029532574117
  rhythmicContrast: 0.8858544488903135
purpose: []
